# Generated by Django 2.2.10 on 2020-08-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_request', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineUser',
        ),
    ]
