# Generated by Django 3.2.9 on 2021-11-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_request', '0002_delete_machineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
