# Generated by Django 4.0.6 on 2023-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_request', '0003_auto_20211106_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingRoomCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('json', models.TextField()),
            ],
        ),
    ]
